# Generated by Django 3.2.13 on 2022-11-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to='users'),
            preserve_default=False,
        ),
    ]
